### ISSUE TITLE
When I log in, if I have 0 wallets in the Database, I am prompted to create one.

### ISSUE THREAD

**Issue by worace** [jdliss/clarkebase#4]
Behind the Scenes, this should Generate an RSA private key
- key should be 2048 bits
- key should get stored in the DB in some format so that it can later be used

**Comment by pindell-matt** [comment]
Waiting to close, currently have issues with testing AJAX - functionality is there, though.

**Comment by worace** [comment]
what does it need ajax for? just put a button. "Welcome to clarkebase. Looks like you don't have a wallet. One will be created for you automatically. <OK>"

**Comment by worace** [comment]
also if it's a pain don't even prompt them. Just create the wallet on signup.

**Comment by Jbern16** [comment]
We liked the idea of the user interacting to create a wallet by pressing a
button. Instead of one auto generating for them. From a user's perspective
is that not needed?

**Comment by worace** [comment]
i meanit would be kind of cute but i mostly want it to work. we need to get the basic stuff working even if it's janky. if the AJAX is taking you more than 15 minutes, you should skip it.
